import React, { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'es' | 'ru' | 'ht';

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.locations': 'Locations',
    'nav.blog': 'Health Blog',
    'nav.partners': 'Partners',
    'nav.contact': 'Contact',
    'nav.pitch': 'Investor Pitch',
    'nav.enroll': 'Enroll Now',
    'nav.schedule': 'Schedule a Demo',
    'seo.title': 'Cedexx | Better Care. Here. Now.',
    'seo.description': 'Healthcare access designed for modern life — affordable 24/7 telemedicine, mental wellness support, and prescription access without insurance.',
    'hero.title': 'Better Care. Here. Now.',
    'hero.subtitle': 'Provider access in your pocket',
    'hero.cta1': 'Start Membership',
    'hero.cta2': 'Partner With CEDEXX',
    'hero.cta3': 'Our Mission',
    'trust.label': 'Trusted healthcare access for individuals, families, employers, and organizations.',
    'serve.title': 'Who We Serve',
    'serve.card1.title': 'Families & Parents',
    'serve.card1.desc': 'Helping parents solve everyday health requirements with ease.',
    'serve.card1.cta': 'Learn More',
    'serve.card2.title': 'Employers & Groups',
    'serve.card2.desc': 'Affordable healthcare benefits that employees actually use.',
    'serve.card2.cta': 'Employer Solutions',
    'serve.card3.title': 'Security & Compliance',
    'serve.card3.desc': 'HIPAA-compliant platform for your peace of mind.',
    'serve.card3.cta': 'Our Security',
    'serve.card4.title': 'Student Housing & Hotels',
    'serve.card4.desc': 'Scalable healthcare access as a premium property amenity.',
    'serve.card4.cta': 'Scale Your Property',
    'property.title': 'Hospitality & Multi-Residential Scale',
    'property.p1': 'Built-in Student Housing Wellness',
    'property.p2': 'Multifamily "Rent-Included" Access',
    'property.p3': 'Hotel Guest Virtual Concierge',
    'property.p4': 'Revenue-Minded Amenity Models',
    'pressure.title': 'Secure healthcare access that moves with you—wherever you go, whenever you need it.',
    'pressure.p1': 'No insurance premiums',
    'pressure.p2': 'No co-pays',
    'pressure.p3': 'No urgent care wait times',
    'pressure.p4': 'No scheduling delays',
    'pressure.footer': "Simple pricing designed to make healthcare more accessible.",
    'how.title': 'Built for Everyday Life',
    'how.step1.title': 'Connect Instantly',
    'how.step1.desc': 'Consult in under 15 minutes',
    'how.step2.title': 'Get Care',
    'how.step2.desc': 'Licensed physician join in minutes',
    'how.step3.title': 'Digital Prescriptions',
    'how.step3.desc': 'Sent instantly to your local pharmacy',
    'outcomes.title': 'A Smarter Healthcare Access Model',
    'outcomes.card1': '24/7 Telemedicine',
    'outcomes.card2': 'Mental Wellness Support',
    'outcomes.card3': 'Prescription Access',
    'why.title': 'Why Cedexx Wins',
    'why.f1': 'One App. One Membership.',
    'why.f2': 'Immediate Care.',
    'why.f3': 'No Insurance Required.',
    'why.f4': 'Better Care, Anywhere.',
    'disclaimer.text': 'Cedexx is a technology platform and is NOT a healthcare provider. We do not provide medical advice, diagnosis, or treatment. All providers are independent contractors. For emergencies, call 911 immediately. Cedexx providers do not prescribe controlled substances.',
    'contact.title': 'Contact Us',
    'contact.subtitle': "Reach out to our team and we'll get back to you within one business day.",
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.company': 'Company / Organization',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sent': "Thank you! We'll be in touch soon.",
    'footer.tagline': 'Better Care. Here. Now. — National Digital Healthcare Platform',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Join Our Network',
    'plans.individual': '$14.99/month',
    'plans.family': '$27.99/month',
    'plans.family.desc': 'Coverage for up to 4 family members'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.locations': 'Ubicaciones',
    'nav.blog': 'Blog de Salud',
    'nav.partners': 'Aliados',
    'nav.contact': 'Contacto',
    'nav.pitch': 'Inversionistas',
    'nav.enroll': 'Inscríbete',
    'nav.schedule': 'Agendar Demo',
    'seo.title': 'Cedexx | Mejor Atención. Aquí. Ahora.',
    'seo.description': 'Acceso médico diseñado para la vida moderna: telemedicina 24/7, bienestar mental y recetas digitales sin necesidad de seguro.',
    'hero.title': 'Mejor Atención. Aquí. Ahora.',
    'hero.subtitle': 'Acceso médico diseñado para la vida moderna: telemedicina 24/7 asequible, apoyo psicológico y recetas digitales, sin primas de seguro ni tiempos de espera.',
    'hero.cta1': 'Comienza tu Membresía',
    'hero.cta2': 'Haz una Alianza con CEDEXX',
    'hero.cta3': 'Nuestra Misión',
    'trust.label': 'Acceso médico confiable para individuos, familias, empresas y organizaciones.',
    'serve.title': 'A Quién Servimos',
    'serve.card1.title': 'Familias y Padres',
    'serve.card1.desc': 'Ayudamos a los padres a resolver necesidades de salud diarias con total facilidad.',
    'serve.card1.cta': 'Saber Más',
    'serve.card2.title': 'Empresas y Grupos',
    'serve.card2.desc': 'Beneficios de salud asequibles que tus empleados realmente valorarán.',
    'serve.card2.cta': 'Soluciones Corporativas',
    'serve.card3.title': 'Seguridad y Privacidad',
    'serve.card3.desc': 'Plataforma con cumplimiento HIPAA para tu total tranquilidad.',
    'serve.card3.cta': 'Nuestra Seguridad',
    'serve.card4.title': 'Student Housing y Hoteles',
    'serve.card4.desc': 'Acceso médico escalable como un beneficio premium para tu propiedad.',
    'serve.card4.cta': 'Potencia tu Propiedad',
    'property.title': 'Escala en Propiedades y Hospitalidad',
    'property.p1': 'Bienestar para Residencias Estudiantiles',
    'property.p2': 'Acceso médico incluido en la renta',
    'property.p3': 'Conserjería Virtual para Huéspedes',
    'property.p4': 'Modelos de ingresos por beneficios adicionales',
    'pressure.title': 'Acceso médico seguro que se mueve contigo, donde sea y cuando lo necesites.',
    'pressure.p1': 'Sin primas de seguro',
    'pressure.p2': 'Sin copagos',
    'pressure.p3': 'Sin esperas en urgencias',
    'pressure.p4': 'Sin demoras en citas',
    'pressure.footer': 'Precios simples diseñados para que la salud sea accesible para todos.',
    'how.title': 'Diseñado para tu Vida Diaria',
    'how.step1.title': 'Conexión Instantánea',
    'how.step1.desc': 'Consulta médica en menos de 15 minutos',
    'how.step2.title': 'Recibe Atención',
    'how.step2.desc': 'Médicos certificados conectados en minutos',
    'how.step3.title': 'Recetas Digitales',
    'how.step3.desc': 'Enviadas directamente a tu farmacia local',
    'outcomes.title': 'Un Modelo de Salud más Inteligente',
    'outcomes.card1': 'Telemedicina 24/7',
    'outcomes.card2': 'Bienestar Mental',
    'outcomes.card3': 'Acceso a Recetas',
    'why.title': 'Por Qué Elegir Cedexx',
    'why.f1': 'Una App. Una Membresía.',
    'why.f2': 'Atención Inmediata.',
    'why.f3': 'Sin Necesidad de Seguro.',
    'why.f4': 'Mejor Atención, Donde Sea.',
    'blog.title': 'Blog de Salud',
    'disclaimer.text': 'Cedexx es una plataforma tecnológica y NO es un proveedor de atención médica. No proporcionamos consejos médicos, diagnósticos ni tratamiento. Todos los médicos son contratistas independientes. En caso de emergencia, llame al 911 de inmediato.',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Escríbenos y nuestro equipo te responderá en máximo un día hábil.',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Correo Electrónico',
    'contact.company': 'Empresa / Organización',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sent': '¡Gracias! Nos pondremos en contacto pronto.',
    'footer.tagline': 'Mejor Atención. Aquí. Ahora. — Salud digital a tu alcance.',
    'footer.links': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Únete a Nuestra Red',
    'plans.individual': '$14.99/mes',
    'plans.family': '$27.99/mes',
    'plans.family.desc': 'Cobertura para todo tu núcleo familiar (hasta 4 miembros)'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.locations': 'Адреса',
    'nav.blog': 'Блог',
    'nav.partners': 'Партнёры',
    'nav.contact': 'Контакты',
    'nav.pitch': 'Для инвесторов',
    'nav.enroll': 'Записаться',
    'nav.schedule': 'Демо',
    'seo.title': 'Cedexx | Лучшая помощь. Здесь. Сейчас.',
    'seo.description': 'Доступ к здравоохранению для современной жизни: доступная телемедицина 24/7, поддержка психического здоровья и рецепты без страховки.',
    'hero.title': 'Лучшая помощь. Здесь. Сейчас.',
    'hero.subtitle': 'Доступ к здравоохранению для современной жизни: доступная телемедицина 24/7, поддержка психического здоровья и рецепты без страховых взносов и очередей.',
    'hero.cta1': 'Начать членство',
    'hero.cta2': 'Стать партнером CEDEXX',
    'hero.cta3': 'Наша миссия',
    'trust.label': 'Надежный доступ к медицине для частных лиц, семей и работодателей.',
    'serve.title': 'Кому мы служим',
    'serve.card1.title': 'Семьи и родители',
    'serve.card1.desc': 'Помогаем родителям легко решать повседневные вопросы здоровья.',
    'serve.card1.cta': 'Узнать больше',
    'serve.card2.title': 'Работодатели и группы',
    'serve.card2.desc': 'Доступные медицинские льготы, которыми сотрудники действительно пользуются.',
    'serve.card2.cta': 'Решения для бизнеса',
    'serve.card3.title': 'Безопасность и соответствие',
    'serve.card3.desc': 'Платформа, соответствующая HIPAA, для вашего спокойствия.',
    'serve.card3.cta': 'Наша защита',
    'serve.card4.title': 'Жилье и Отели',
    'serve.card4.desc': 'Масштабируемый доступ к медицине как премиальная услуга.',
    'serve.card4.cta': 'Масштабируйте объект',
    'property.title': 'Масштаб в жилье и отелях',
    'property.p1': 'Оздоровление в студенческом жилье',
    'property.p2': 'Доступ, включенный в аренду',
    'property.p3': 'Виртуальный консьерж для гостей',
    'property.p4': 'Доходные модели услуг',
    'pressure.title': 'Безопасный доступ к медицине',
    'pressure.p1': 'Без страховых взносов',
    'pressure.p2': 'Без доплат (co-pays)',
    'pressure.p3': 'Без очередей в скорой',
    'pressure.p4': 'Без задержек записи',
    'pressure.footer': 'Простая цена, делающая медицину доступнее.',
    'how.title': 'Создано для повседневной жизни',
    'how.step1.title': 'Мгновенная связь',
    'how.step1.desc': 'Консультация менее чем за 15 минут',
    'how.step2.title': 'Получите помощь',
    'how.step2.desc': 'Лицензированный врач подключится за минуты',
    'how.step3.title': 'Цифровые рецепты',
    'how.step3.desc': 'Отправляются мгновенно в вашу аптеку',
    'outcomes.title': 'Умная модель доступа к медицине',
    'outcomes.card1': 'Телемедицина 24/7',
    'outcomes.card2': 'Поддержка ментального здоровья',
    'outcomes.card3': 'Доступ к рецептам',
    'why.title': 'Почему Cedexx побеждает',
    'why.f1': 'Одно приложение. Одна подписка.',
    'why.f2': 'Немедленная помощь.',
    'why.f3': 'Страховка не требуется.',
    'why.f4': 'Лучшая помощь везде.',
    'disclaimer.text': 'Cedexx — это технологическая платформа, и НЕ является поставщиком медицинских услуг. Мы не предоставляем медицинских консультаций, диагностики или лечения. Все поставщики являются независимыми подрядчиками. В экстренных случаях звоните 911.',
    'contact.title': 'Связаться с нами',
    'contact.subtitle': 'Свяжитесь с нами, и мы ответим в течение рабочего дня.',
    'contact.name': 'Полное имя',
    'contact.email': 'Email',
    'contact.company': 'Компания / Организация',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить',
    'contact.sent': 'Спасибо! Мы скоро свяжемся.',
    'footer.tagline': 'Лучшая помощь. Здесь. Сейчас. — Врач у вас под рукой.',
    'footer.links': 'Ссылки',
    'footer.contact': 'Контакты',
    'footer.legal': 'Юридическая инфо',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Присоединяйтесь к сети',
    'plans.individual': '14.99$/мес',
    'plans.family': '27.99$/мес',
    'plans.family.desc': 'Покрытие до 4 членов семьи'
  },
  ht: {
    'nav.home': 'Akèy',
    'nav.about': 'Sou Nou',
    'nav.services': 'Sèvis',
    'nav.locations': 'Kote Nou Yo',
    'nav.blog': 'Blog',
    'nav.partners': 'Patnè',
    'nav.contact': 'Kontak',
    'nav.pitch': 'Pitch Envestisè',
    'nav.enroll': 'Enskri Kounye a',
    'nav.schedule': 'Planifye Demo',
    'seo.title': 'Cedexx | Pi Bon Swen. Isit la. Kounye a.',
    'seo.description': 'Aksè sante pou lavi modèn — telemedsin 24/7 abòdab, sipò sante mantal, ak aksè preskripsyon san asirans.',
    'hero.title': 'Pi Bon Swen. Isit la. Kounye a.',
    'hero.subtitle': 'Aksè sante ki fèt pou lavi modèn — telemedsin 24/7 abòdab, sipò sante mantal, ak aksè ak preskripsyon, san prim asirans oswa reta.',
    'hero.cta1': 'Kòmanse Manm',
    'hero.cta2': 'Vin Patnè CEDEXX',
    'hero.cta3': 'Misyon Nou',
    'trust.label': 'Aksè sante serye pou moun, fanmi, ak anplwayè.',
    'serve.title': 'Kiyès Nou Sèvi',
    'serve.card1.title': 'Fanmi ak Paran',
    'serve.card1.desc': 'Ede paran yo rezoud bezwen sante chak jou ak fasilite.',
    'serve.card1.cta': 'Aprann Plis',
    'serve.card2.title': 'Anplwayè ak Gwoup',
    'serve.card2.desc': 'Benefis sante abòdab ke anplwaye yo vrèman itilize.',
    'serve.card2.cta': 'Solisyon pou Anplwayè',
    'serve.card3.title': 'San Danje ak Sekirite',
    'serve.card3.desc': 'Platfòm ki respekte HIPAA pou lapè lespri ou.',
    'serve.card3.cta': 'Sekirite Nou',
    'serve.card4.title': 'Lojman Elèv ak Otèl',
    'serve.card4.desc': 'Aksè sante ki ka grandi kòm yon amènite pwopriyete premium.',
    'serve.card4.cta': 'Grandis Pwopriyete w',
    'property.title': 'Echèl Rezidansyèl ak Ospitalite',
    'property.p1': 'Byennèt Entegre nan Lojman Elèv',
    'property.p2': 'Aksè "Enkli nan Lwaye" pou Multifanmi',
    'property.p3': 'Consierge Virtuel pou Envite',
    'property.p4': 'Modèl Revni Amènite',
    'pressure.title': 'Aksè Sante Sekirite',
    'pressure.p1': 'Pa gen prim asirans',
    'pressure.p2': 'Pa gen ko-peyman',
    'pressure.p3': 'Pa gen tann nan ijans',
    'pressure.p4': 'Pa gen reta nan randevou',
    'pressure.footer': 'Pri senp ki fèt pou fè sante pi fasil pou jwenn.',
    'how.title': 'Fèt pou Lavi Chak Jou',
    'how.step1.title': 'Konekte Touswit',
    'how.step1.desc': 'Konsiltasyon nan mwens pase 15 minit',
    'how.step2.title': 'Jwenn Swen',
    'how.step2.desc': 'Doktè sètifye nan kèk minit',
    'how.step3.title': 'Preskripsyon Dijital',
    'how.step3.desc': 'Voye touswit nan famasi ou',
    'outcomes.title': 'Yon Modèl Aksè Sante Ki Pi Entelijan',
    'outcomes.card1': 'Telemedsin 24/7',
    'outcomes.card2': 'Sipò Sante Mantal',
    'outcomes.card3': 'Aksè ak Preskripsyon',
    'why.title': 'Poukisa Cedexx Genyen',
    'why.f1': 'Yon Sèl App. Yon Sèl Manm.',
    'why.f2': 'Swen Imedya.',
    'why.f3': 'Pa Bezwen Asirans.',
    'why.f4': 'Pi Bon Swen, Nenpòt kote.',
    'disclaimer.text': 'Cedexx se yon platfòm teknoloji e li PA yon founisè swen sante. Nou pa bay konsèy medikal, dyagnostik oswa tretman. Tout founisè yo se antreprenè endepandan. Pou ijans, rele 911.',
    'contact.title': 'Kontakte Nou',
    'contact.subtitle': 'Kontakte ekip nou an epi n ap reponn ou nan yon jou travay.',
    'contact.name': 'Non Konplè',
    'contact.email': 'Adrès Imel',
    'contact.company': 'Konpayi / Òganizasyon',
    'contact.message': 'Mesaj',
    'contact.send': 'Voye Mesaj',
    'contact.sent': 'Mèsi! N ap kontakte w talè.',
    'footer.tagline': 'Pi Bon Swen. Isit la. Kounye a. — Doktè nan pwent dwèt ou.',
    'footer.links': 'Lyen Rapid',
    'footer.contact': 'Kontak',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Antre nan Rezo Nou an',
    'plans.individual': '$14.99/pa mwa',
    'plans.family': '$27.99/pa mwa',
    'plans.family.desc': 'Kouvèti pou jiska 4 moun nan fanmi an'
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string): string => translations[lang][key] ?? translations['en'][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
