import React, { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'es' | 'ru' | 'ht';

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.blog': 'Health Blog',
    'nav.partners': 'Partners',
    'nav.contact': 'Contact',
    'nav.pitch': 'Investor Pitch',
    'nav.enroll': 'Enroll Now',
    'seo.title': 'Cedexx | Better Care. Here. Now.',
    'seo.description': 'Healthcare access designed for modern life — affordable 24/7 telemedicine, mental wellness support, and prescription access without insurance.',
    'hero.title': 'Better Care. Here. Now.',
    'hero.subtitle': 'Provider access in your pocket',
    'hero.cta1': 'Start Membership',
    'hero.cta2': 'Partner With CEDEXX',
    'trust.label': 'Trusted healthcare access for individuals, families, employers, and organizations.',
    'serve.title': 'Who We Serve',
    'serve.card1.title': 'Families & Parents',
    'serve.card1.desc': 'Helping parents solve everyday health requirements with ease.',
    'serve.card2.title': 'Employers & Groups',
    'serve.card2.desc': 'Affordable healthcare benefits that employees actually use.',
    'serve.card3.title': 'Security & Compliance',
    'serve.card3.desc': 'HIPAA-compliant platform for your peace of mind.',
    'serve.card4.title': 'Student Housing & Hotels',
    'serve.card4.desc': 'Scalable healthcare access as a premium property amenity.',
    'how.title': 'Built for Everyday Life',
    'how.step1.title': 'Connect Instantly',
    'how.step1.desc': 'Consult in under 15 minutes',
    'how.step2.title': 'Get Care',
    'how.step2.desc': 'Licensed physician join in minutes',
    'how.step3.title': 'Digital Prescriptions',
    'how.step3.desc': 'Sent instantly to your local pharmacy',
    'outcomes.title': 'A Smarter Healthcare Access Model',
    'outcomes.card1': '24/7 Telemedicine',
    'outcomes.card2': 'Mental Wellness Support',
    'outcomes.card3': 'Prescription Access',
    'disclaimer.text': 'Cedexx is a technology platform and is NOT a healthcare provider. We do not provide medical advice, diagnosis, or treatment. All providers are independent contractors. For emergencies, call 911 immediately.',
    'contact.title': 'Contact Us',
    'contact.subtitle': "Reach out and we'll get back within one business day.",
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.company': 'Company / Organization',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sent': "Thank you! We'll be in touch soon.",
    'footer.tagline': 'Better Care. Here. Now. — National Digital Healthcare Platform',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'plans.individual': '$14.99/month',
    'plans.family': '$27.99/month',
    'plans.family.desc': 'Coverage for up to 4 family members'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.blog': 'Blog de Salud',
    'nav.partners': 'Aliados',
    'nav.contact': 'Contacto',
    'nav.pitch': 'Inversionistas',
    'nav.enroll': 'Inscríbete',
    'seo.title': 'Cedexx | Mejor Atención. Aquí. Ahora.',
    'seo.description': 'Acceso médico para la vida moderna: telemedicina 24/7, bienestar mental y recetas sin seguro.',
    'hero.title': 'Mejor Atención. Aquí. Ahora.',
    'hero.subtitle': 'Acceso médico en tu bolsillo',
    'hero.cta1': 'Comenzar Membresía',
    'hero.cta2': 'Haz Alianza con CEDEXX',
    'trust.label': 'Acceso médico confiable para individuos, familias y organizaciones.',
    'serve.title': 'A Quién Servimos',
    'serve.card1.title': 'Familias y Padres',
    'serve.card1.desc': 'Ayudamos a resolver necesidades de salud diarias.',
    'serve.card2.title': 'Empresas y Grupos',
    'serve.card2.desc': 'Beneficios de salud asequibles.',
    'serve.card3.title': 'Seguridad y Cumplimiento',
    'serve.card3.desc': 'Plataforma HIPAA para tu tranquilidad.',
    'serve.card4.title': 'Residencias y Hoteles',
    'serve.card4.desc': 'Acceso médico escalable como amejnity premium.',
    'how.title': 'Diseñado para tu Vida',
    'how.step1.title': 'Conexión Instantánea',
    'how.step1.desc': 'Consulta en menos de 15 minutos',
    'how.step2.title': 'Recibe Atención',
    'how.step2.desc': 'Médicos certificados conectados en minutos',
    'how.step3.title': 'Recetas Digitales',
    'how.step3.desc': 'Enviadas a tu farmacia local',
    'outcomes.title': 'Un Modelo de Salud más Inteligente',
    'outcomes.card1': 'Telemedicina 24/7',
    'outcomes.card2': 'Bienestar Mental',
    'outcomes.card3': 'Acceso a Recetas',
    'disclaimer.text': 'Cedexx es una plataforma tecnológica y NO es un proveedor médico. No damos consejos médicos ni tratamiento. En emergencias llame al 911.',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Escríbenos y responderemos en un día hábil.',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Correo',
    'contact.company': 'Empresa',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar',
    'contact.sent': '¡Gracias! Nos pondremos en contacto.',
    'footer.tagline': 'Mejor Atención. Aquí. Ahora.',
    'footer.links': 'Enlaces',
    'footer.contact': 'Contacto',
    'footer.legal': 'Legal',
    'plans.individual': '$14.99/mes',
    'plans.family': '$27.99/mes',
    'plans.family.desc': 'Cobertura hasta 4 miembros'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.blog': 'Блог',
    'nav.partners': 'Партнёры',
    'nav.contact': 'Контакты',
    'nav.pitch': 'Инвесторам',
    'nav.enroll': 'Записаться',
    'seo.title': 'Cedexx | Лучшая помощь. Здесь. Сейчас.',
    'hero.title': 'Лучшая помощь. Здесь. Сейчас.',
    'hero.subtitle': 'Доступ к медицине в кармане',
    'hero.cta1': 'Начать членство',
    'hero.cta2': 'Стать партнёром',
    'trust.label': 'Надёжный доступ к медицине.',
    'serve.title': 'Кому мы служим',
    'serve.card1.title': 'Семьи и родители',
    'serve.card1.desc': 'Решаем вопросы здоровья каждый день.',
    'serve.card2.title': 'Работодатели и группы',
    'serve.card2.desc': 'Доступные медицинские льготы.',
    'serve.card3.title': 'Безопасность',
    'serve.card3.desc': 'Платформа HIPAA для спокойствия.',
    'serve.card4.title': 'Жильё и отели',
    'serve.card4.desc': 'Масштабируемый доступ как услуга.',
    'how.title': 'Создано для жизни',
    'how.step1.title': 'Мгновенная связь',
    'how.step1.desc': 'Консультация за 15 минут',
    'how.step2.title': 'Получите помощь',
    'how.step2.desc': 'Лицензированный врач за минуты',
    'how.step3.title': 'Цифровые рецепты',
    'how.step3.desc': 'Отправляются в аптеку',
    'outcomes.title': 'Умная модель доступа',
    'outcomes.card1': 'Телемедицина 24/7',
    'outcomes.card2': 'Психическое здоровье',
    'outcomes.card3': 'Доступ к рецептам',
    'disclaimer.text': 'Cedexx — технологическая платформа, НЕ поставщик медицины. В экстренных случаях звоните 911.',
    'contact.title': 'Связаться',
    'contact.subtitle': 'Ответим в течение рабочего дня.',
    'contact.name': 'Имя',
    'contact.email': 'Email',
    'contact.company': 'Компания',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить',
    'contact.sent': 'Спасибо! Скоро свяжемся.',
    'footer.tagline': 'Лучшая помощь. Здесь. Сейчас.',
    'footer.links': 'Ссылки',
    'footer.contact': 'Контакты',
    'footer.legal': 'Юридическое',
    'plans.individual': '14.99$/мес',
    'plans.family': '27.99$/мес',
    'plans.family.desc': 'До 4 членов семьи'
  },
  ht: {
    'nav.home': 'Akèy',
    'nav.about': 'Sou Nou',
    'nav.services': 'Sèvis',
    'nav.blog': 'Blog',
    'nav.partners': 'Patnè',
    'nav.contact': 'Kontak',
    'nav.pitch': 'Pitch envestisè',
    'nav.enroll': 'Enskri',
    'seo.title': 'Cedexx | Pi Bon Swen. Isit. Kounye.',
    'hero.title': 'Pi Bon Swen. Isit. Kounye.',
    'hero.subtitle': 'Aksè doktè nan pwent dwèt ou',
    'hero.cta1': 'Kòmanse Manm',
    'hero.cta2': 'Vin Patnè',
    'trust.label': 'Aksè sante serye pou tout moun.',
    'serve.title': 'Kiyès Nou Sèvi',
    'serve.card1.title': 'Fanmi ak Paran',
    'serve.card1.desc': 'Ede rezoud bezwen sante chak jou.',
    'serve.card2.title': 'Anplwayè ak Gwoup',
    'serve.card2.desc': 'Benefis sante abòdab.',
    'serve.card3.title': 'Sekirite ak Konfòmite',
    'serve.card3.desc': 'Platfòm HIPAA pou lapè ou.',
    'serve.card4.title': 'Lojman ak Otèl',
    'serve.card4.desc': 'Aksè sante ki ka grandi.',
    'how.title': 'Fèt pou Lavi Chak Jou',
    'how.step1.title': 'Konekte Touswit',
    'how.step1.desc': 'Konsiltasyon nan mwens pase 15 minit',
    'how.step2.title': 'Jwenn Swen',
    'how.step2.desc': 'Doktè sètifye nan kèk minit',
    'how.step3.title': 'Preskripsyon Dijital',
    'how.step3.desc': 'Voye nan famasi ou',
    'outcomes.title': 'Yon Modèl Aksè Ki Pi Entelijan',
    'outcomes.card1': 'Telemedsin 24/7',
    'outcomes.card2': 'Sipò Sante Mantal',
    'outcomes.card3': 'Aksè Preskripsyon',
    'disclaimer.text': 'Cedexx se yon platfòm teknoloji e PA yon founisè sante. Pou ijans, rele 911.',
    'contact.title': 'Kontakte Nou',
    'contact.subtitle': 'N ap reponn ou nan yon jou travay.',
    'contact.name': 'Non Konplè',
    'contact.email': 'Imel',
    'contact.company': 'Konpayi',
    'contact.message': 'Mesaj',
    'contact.send': 'Voye',
    'contact.sent': 'Mèsi! N ap kontakte w.',
    'footer.tagline': 'Pi Bon Swen. Isit. Kounye.',
    'footer.links': 'Lyen',
    'footer.contact': 'Kontak',
    'footer.legal': 'Legal',
    'plans.individual': '$14.99/pa mwa',
    'plans.family': '$27.99/pa mwa',
    'plans.family.desc': 'Jiska 4 moun nan fanmi'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string): string => translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
