import React, { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'es' | 'ru' | 'ht';

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.locations': 'Locations',
    'nav.blog': 'Health Blog',
    'nav.partners': 'Partners',
    'nav.contact': 'Contact',
    'nav.pitch': 'Investor Pitch',
    'nav.enroll': 'Start Membership',
    'nav.schedule': 'Start Demo',
    'seo.title': 'Cedexx | Better Care. Here. Now.',
    'seo.description': 'A premium wellness amenity connecting residents to Lyric Health board-certified providers for everyday care, prescriptions, and mental wellness support.',
    'hero.title': 'Better Care. Here. Now.',
    'hero.subtitle': 'Immediate, secure access to healthcare—whenever and wherever life demands it.',
    'hero.platform_desc': 'CEDEXX is a digital healthcare access platform connecting members to Lyric Health licensed providers for everyday care, prescriptions, and mental wellness support—all through one simple monthly membership.',
    'hero.amenity_desc': 'A modern wellness amenity designed for individuals, families, and residential communities.',
    'hero.cta1': 'Start Membership',
    'hero.cta2': 'Partner With CEDEXX',
    'hero.cta3': 'Our Mission',
    'trust.label': 'Trusted healthcare access designed for individuals, families and modern residential communities.',
    'features.access.title': '24/7 Provider Access',
    'features.access.desc': 'Care anytime, day or night.',
    'features.speed.title': 'See a Doctor in Minutes',
    'features.speed.desc': 'Connect in under 15 minutes.',
    'features.membership.title': 'Membership Pricing',
    'features.membership.desc': 'Starting at $14.99/month. No insurance required.',
    'features.secure.title': 'Secure & Private Platform',
    'features.secure.desc': 'HIPAA-compliant and confidential.',
    'serve.title': 'Our Four Pillars',
    'serve.card1.title': 'Hospitality Solutions',
    'serve.card1.desc': 'Facilitating concierge care access for your hotel guests.',
    'serve.card1.cta': 'Learn More',
    'serve.card2.title': 'Affiliate Opportunities',
    'serve.card2.desc': 'Telecommunication and marketing partnerships built for scale.',
    'serve.card2.cta': 'Learn More',
    'serve.card3.title': 'ACCESSIBILITY',
    'serve.card3.desc': 'Connecting residents and workforce to immediate physician access.',
    'serve.card3.cta': 'ACCESSIBILITY',
    'serve.card4.title': 'Student/Corporate Housing & Multifamily',
    'serve.card4.desc': 'Set your Housing Asset apart by incorporating the value of accessible mobile healthcare.',
    'serve.card4.cta': 'Scale Your Property',
    'pressure.title': 'Secure healthcare access that moves with you—wherever you go, whenever you need it.',
    'how.title': 'Built for Everyday Life',
    'how.step1.title': 'Connect Instantly',
    'how.step1.desc': 'Typically connect in under 15 minutes',
    'how.step2.title': 'Consult with Providers',
    'how.step2.desc': 'Licensed physicians join in minutes',
    'how.step3.title': 'Digital Prescriptions',
    'how.step3.desc': 'Sent instantly to your local pharmacy',
    'outcomes.title': 'A Smarter Healthcare Access Model',
    'outcomes.card1': '24/7 Telemedicine',
    'outcomes.card2': 'Mental Wellness Support',
    'outcomes.card3': 'Prescription Access',
    'why.title': 'Why Cedexx Wins',
    'why.f1': 'One App. One Membership.',
    'why.f2': 'Immediate Care.',
    'why.f3': 'No Insurance Required.',
    'why.f4': 'Better Care. Here. Now.',
    'disclaimer.text': 'CEDEXX is a technology platform. Healthcare services are provided by Lyric Health. All services are delivered by Lyric Health licensed providers. Lyric Health services are not a substitute for health insurance.',
    'contact.title': 'Contact Us',
    'contact.subtitle': "Reach out to our team and we'll get back to you within one business day.",
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.company': 'Company / Organization',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sent': "Thank you! We'll be in touch soon.",
    'footer.tagline': 'Better Care. Here. Now. Keep It in Your Back Pocket.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Join Our Network',
    'plans.individual': '$14.99/month',
    'plans.family': '$34.99/month',
    'plans.family.desc': 'Coverage for up to 7 family members',
    'partners.hero.title': 'Strategic Partnerships',
    'partners.hero.subtitle': 'Better Care. Here. Now. Keep It in Your Back Pocket.',
    'partners.ecosystems.title': 'Ecosystems We Serve',
    'partners.ecosystems.subtitle': 'Industry leaders trust Cedexx to facilitate immediate healthcare access.',
    'partners.ecosystems.quote': 'Healthcare should move with modern life—immediate, dependable, and accessible wherever people live, work, travel, and grow.',
    'partners.ecosystems.workforce.title': 'Transportation & Workforce',
    'partners.ecosystems.workforce.desc': 'CEDEXX enables modern digital healthcare access for workforce populations of all kinds. From trucking and logistics to hospitality and corporate teams, we provide affordable physician connections that fit any schedule.',
    'partners.ecosystems.individuals.title': 'Individuals & Families',
    'partners.ecosystems.individuals.desc': 'For individuals and families, CEDEXX provides a practical layer of access—whether complementing existing coverage or offering affordable connections when traditional insurance falls short.',
    'partners.ecosystems.housing.title': 'Housing & Communities',
    'partners.ecosystems.housing.desc': 'Through strategic partnerships in multifamily and student housing, we help asset managers introduce modern healthcare access as a premium lifestyle amenity.',
    'partners.ecosystems.hospitality.title': 'Hospitality Solutions',
    'partners.ecosystems.hospitality.desc': 'Concierge telehealth access for hotel guests—Connecting hotel guests to licensed physicians from the comfort of their room, including travel documentation when needed.',
    'partners.ecosystems.footer': 'From home to campus to travel, CEDEXX keeps trusted access within reach.',
    'partners.form.badge': 'JOIN THE NETWORK',
    'partners.form.title': 'Partner With Cedexx',
    'partners.form.subtitle': 'Explore strategic integration opportunities across our key amenity pillars and physician networks.',
    'role.physician': 'Physician',
    'role.affiliate': 'Affiliate Partner',
    'pricing.badge': 'Membership Plans',
    'pricing.title': 'Simple. Transparent. Affordable.',
    'pricing.subtitle': 'Choose the plan that fits your life. All plans include 24/7 access, no hidden fees, and no insurance required.',
    'pricing.note': 'No insurance required. Cancel anytime. HIPAA compliant.',
    'pricing.popular': 'Most Popular',
    'pricing.plan.carenow.name': 'CareNow',
    'pricing.plan.carenow.desc': 'Virtual Urgent Care for you and your household up to 7 dependents.',
    'pricing.plan.carenow.cta': 'Start CareNow',
    'pricing.plan.carenow-mental.name': 'CareNow + Mental Wellness',
    'pricing.plan.carenow-mental.subtitle': 'CareNow + $8',
    'pricing.plan.carenow-mental.desc': 'Everything in CareNow, plus:',
    'pricing.plan.carenow-mental.cta': 'Start CareNow + Mental',
    'pricing.plan.mental.name': 'Mental Wellness',
    'pricing.plan.mental.desc': 'Perfect for members seeking mental health support.',
    'pricing.plan.mental.cta': 'Start Mental Wellness',
    'pricing.plan.carecomplete.name': 'CareComplete',
    'pricing.plan.carecomplete.subtitle': 'Complete Virtual Primary Care',
    'pricing.plan.carecomplete.desc': 'Individual Membership. A comprehensive virtual healthcare membership designed for preventive care, ongoing health management, and whole-person wellness.',
    'pricing.plan.carecomplete.cta': 'Start CareComplete',
    'pricing.plan.carecomplete-family.name': 'CareComplete Family',
    'pricing.plan.carecomplete-family.subtitle': 'Complete Family Virtual Care',
    'pricing.plan.carecomplete-family.desc': 'Coverage for up to seven household members, with every member receiving comprehensive virtual healthcare.',
    'pricing.plan.carecomplete-family.cta': 'Start Family Plan',
    'enroll.plan.carenow.name': 'CareNow',
    'enroll.plan.carenow.price': '$14.99',
    'enroll.plan.carenow.desc': 'Virtual Urgent Care for you and your household up to 7 dependents.',
    'enroll.plan.carenow-mental.name': 'CareNow + Mental Wellness',
    'enroll.plan.carenow-mental.price': '$22.99',
    'enroll.plan.carenow-mental.desc': 'Everything in CareNow, plus mental health support.',
    'enroll.plan.mental.name': 'Mental Wellness',
    'enroll.plan.mental.price': '$14.99',
    'enroll.plan.mental.desc': 'Standalone mental health support.',
    'enroll.plan.carecomplete.name': 'CareComplete',
    'enroll.plan.carecomplete.price': '$34.99',
    'enroll.plan.carecomplete.desc': 'Complete Virtual Primary Care for individuals.',
    'enroll.plan.carecomplete-family.name': 'CareComplete Family',
    'enroll.plan.carecomplete-family.price': '$52.99',
    'enroll.plan.carecomplete-family.desc': 'Complete Family Virtual Care for up to 7 members.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.locations': 'Ubicaciones',
    'nav.blog': 'Blog de Salud',
    'nav.partners': 'Aliados',
    'nav.contact': 'Contacto',
    'nav.pitch': 'Inversionistas',
    'nav.enroll': 'Inscríbete',
    'nav.schedule': 'Agendar Demo',
    'seo.title': 'Cedexx | Mejor Atención. Aquí. Ahora.',
    'seo.description': 'Un servicio de bienestar premium que conecta a los residentes con proveedores independientes certificados para atención diaria, recetas y salud mental.',
    'hero.title': 'Mejor Atención. Aquí. Ahora.',
    'hero.subtitle': 'Acceso inmediato a la atención en su bolsillo.',
    'hero.cta1': 'Comienza tu Membresía',
    'hero.cta2': 'Haz una Alianza con CEDEXX',
    'hero.cta3': 'Nuestra Misión',
    'trust.label': 'Acceso médico confiable diseñado para individuos, familias y comunidades residenciales modernas.',
    'serve.title': 'Nuestros Cuatro Pilares',
    'serve.card1.title': 'Soluciones de Hospitalidad',
    'serve.card1.desc': 'Facilitando el acceso a servicios de conserjería médica para sus huéspedes.',
    'serve.card1.cta': 'Saber Más',
    'serve.card2.title': 'Oportunidades de Afiliados',
    'serve.card2.desc': 'Alianzas de telecomunicaciones y marketing diseñadas para escalar.',
    'serve.card2.cta': 'Saber Más',
    'serve.card3.title': 'ACCESIBILIDAD',
    'serve.card3.desc': 'Conectando a residentes y trabajadores con acceso médico inmediato.',
    'serve.card3.cta': 'ACCESIBILITE',
    'serve.card4.title': 'Vivienda Estudiantil/Corporativa y Multifamiliar',
    'serve.card4.desc': 'Destaque su activo inmobiliario incorporando el valor del acceso médico móvil.',
    'serve.card4.cta': 'Potencia tu Propiedad',
    'pressure.title': 'Acceso médico seguro que se mueve contigo, donde sea y cuando lo necesites.',
    'how.title': 'Diseñado para tu Vida Diaria',
    'how.step1.title': 'Conexión Instantánea',
    'how.step1.desc': 'Conexión típica en menos de 15 minutos',
    'how.step2.title': 'Consulte con Proveedores',
    'how.step2.desc': 'Médicos certificados se conectan en minutos',
    'how.step3.title': 'Recetas Digitales',
    'how.step3.desc': 'Enviadas directamente a tu farmacia local',
    'outcomes.title': 'Un Modelo de Salud más Inteligente',
    'outcomes.card1': 'Telemedicina 24/7',
    'outcomes.card2': 'Bienestar Mental',
    'outcomes.card3': 'Acceso a Recetas',
    'why.title': 'Por Qué Elegir Cedexx',
    'why.f1': 'Una sola aplicación. Una sola membresía.',
    'why.f2': 'Atención inmediata.',
    'why.f3': 'No se requiere seguro.',
    'why.f4': 'Mejor Atención. Aquí. Ahora.',
    'disclaimer.text': 'Cedexx es una plataforma tecnológica y NO es un proveedor de atención médica. No proporcionamos consejos médicos, diagnósticos ni tratamiento. Todos los médicos son contratistas independientes. En caso de emergencia, llame al 911 de inmediato. Esta plataforma no es un sustituto del seguro médico.',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Escríbenos y nuestro equipo te responderá en máximo un día hábil.',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Correo Electrónico',
    'contact.company': 'Empresa / Organización',
    'contact.message': 'Message',
    'contact.send': 'Enviar Mensaje',
    'contact.sent': '¡Gracias! Nos pondremos en contacto pronto.',
    'footer.tagline': 'Mejor Atención. Aquí. Ahora. Mantenlo en tu bolsillo.',
    'footer.links': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Únete a Nuestra Red',
    'plans.individual': '$14.99/mes',
    'plans.family': '$34.99/mes',
    'plans.family.desc': 'Cobertura para todo tu núcleo familiar (hasta 4 miembros)',
    'partners.hero.title': 'Alianzas Estratégicas',
    'partners.hero.subtitle': 'Mejor Atención. Aquí. Ahora. Mantenlo en tu bolsillo.',
    'partners.ecosystems.title': 'Ecosistemas que Servimos',
    'partners.ecosystems.subtitle': 'Líderes de la industria confían en Cedexx para facilitar el acceso médico inmediato.',
    'partners.ecosystems.quote': 'La salud debe moverse con la vida moderna: inmediata, confiable y accesible dondequiera que la gente viva, trabaje, viaje y crezca.',
    'partners.ecosystems.workforce.title': 'Transporte y Fuerza Laboral',
    'partners.ecosystems.workforce.desc': 'CEDEXX permite el acceso a la salud digital moderna para fuerzas laborales de todo tipo. Desde transporte y logística hasta hostelería y equipos corporativos, brindamos conexiones médicas asequibles que se adaptan a cualquier horario.',
    'partners.ecosystems.individuals.title': 'Individuos y Familias',
    'partners.ecosystems.individuals.desc': 'Para individuos y familias, CEDEXX ofrece una capa práctica de acceso, ya sea complementando la cobertura existente o brindando conexiones asequibles.',
    'partners.ecosystems.housing.title': 'Vivienda y Comunidades',
    'partners.ecosystems.housing.desc': 'A través de alianzas estratégicas en viviendas estudiantiles y multifamiliares, ayudamos a los administradores a introducir el acceso médico como una amenidad premium.',
    'partners.ecosystems.hospitality.title': 'Pilar de Hospitalidad',
    'partners.ecosystems.hospitality.desc': 'La hospitalidad es nuestro tercer pilar estratégico, conectando a los viajeros con médicos licenciados desde la comodidad de su habitación.',
    'partners.ecosystems.footer': 'Desde el hogar hasta el campus y los viajes, CEDEXX mantiene el acceso confiable a su alcance.',
    'partners.form.badge': 'ÚNETE A LA RED',
    'partners.form.title': 'Alíate con Cedexx',
    'partners.form.subtitle': 'Explore oportunidades de integración estratégica a través de nuestros pilares de amenidades y redes de médicos.',
    'role.physician': 'Médico',
    'role.affiliate': 'Socio Afiliado'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.locations': 'Адреса',
    'nav.blog': 'Блог',
    'nav.partners': 'Партнёры',
    'nav.contact': 'Контакты',
    'nav.pitch': 'Для инвесторов',
    'nav.enroll': 'Записаться',
    'nav.schedule': 'Демо',
    'seo.title': 'Cedexx | Лучшая помощь. Здесь. Сейчас.',
    'seo.description': 'Премиальный оздоровительный сервис, объединяющий жителей с сертифицированными врачами для лечения, выписки рецептов и поддержки.',
    'hero.title': 'Лучшая помощь. Здесь. Сейчас.',
    'hero.subtitle': 'Немедленный доступ к врачу прямо у вас в кармане.',
    'hero.cta1': 'Начать членство',
    'hero.cta2': 'Стать партнером CEDEXX',
    'hero.cta3': 'Наша миссия',
    'trust.label': 'Надежный доступ к медицине для частных лиц, семей и современных жилых комплексов.',
    'serve.title': 'Наши четыре столпа',
    'serve.card1.title': 'Решения для гостеприимства',
    'serve.card1.desc': 'Обеспечение доступа к медицинской консьерж-службе для гостей вашего отеля.',
    'serve.card1.cta': 'Узнать больше',
    'serve.card2.title': 'Партнерские возможности',
    'serve.card2.desc': 'Телекоммуникационные и маркетинговые партнерства для масштабирования.',
    'serve.card2.cta': 'Узнать больше',
    'serve.card3.title': 'ДОСТУПНОСТЬ',
    'serve.card3.desc': 'Обеспечение немедленного доступа к врачам для жителей и персонала.',
    'serve.card3.cta': 'ДОСТУПНОСТЬ',
    'serve.card4.title': 'Студенческое/корпоративное и жилье',
    'serve.card4.desc': 'Выделите свой объект недвижимости, внедрив доступную мобильную медицину.',
    'serve.card4.cta': 'Масштабируйте объект',
    'pressure.title': 'Безопасный доступ к медицине',
    'how.title': 'Создано для повседневной жизни',
    'how.step1.title': 'Мгновенная связь',
    'how.step1.desc': 'Обычно соединение менее чем за 15 минут',
    'how.step2.title': 'Консультация с врачом',
    'how.step2.desc': 'Лицензированные врачи подключаются за считанные минуты',
    'how.step3.title': 'Цифровые рецепты',
    'how.step3.desc': 'Отправляются мгновенно в вашу аптеку',
    'outcomes.title': 'Умная модель доступа к медицине',
    'outcomes.card1': 'Телемедицина 24/7',
    'outcomes.card2': 'Поддержка ментального здоровья',
    'outcomes.card3': 'Доступ к рецептам',
    'why.title': 'Почему Cedexx побеждает',
    'why.f1': 'Одно приложение. Одно членство.',
    'why.f2': 'Немедленная помощь.',
    'why.f3': 'Страховка не требуется.',
    'why.f4': 'Лучшая помощь. Здесь. Сейчас.',
    'partners.ecosystems.title': 'Экосистемы, которые мы обслуживаем',
    'partners.ecosystems.subtitle': 'Лидеры отрасли доверяют Cedexx обеспечению немедленного медицинского доступа.',
    'partners.ecosystems.quote': 'Медицина должна идти в ногу с современной жизнью — быть немедленной, надежной и доступной везде, где люди живут, работают, путешествуют и растут.',
    'partners.ecosystems.workforce.title': 'Транспорт и Рабочие',
    'partners.ecosystems.workforce.desc': 'CEDEXX обеспечивает доступ к цифровой медицине для рабочих коллективов всех видов. От грузоперевозок и логистики до гостеприимства и корпоративных команд — мы предоставляем доступные медицинские связи для любого графика.',
    'partners.ecosystems.individuals.title': 'Частные лица и семьи',
    'partners.ecosystems.individuals.desc': 'Для частных лиц и семей CEDEXX предлагает практичный уровень доступа, дополняя существующую страховку или предлагая доступные решения.',
    'partners.ecosystems.housing.title': 'Жилье и сообщества',
    'partners.ecosystems.housing.desc': 'Через стратегические партнерства в жилых комплексах мы помогаем управляющим внедрять современную медицину как премиальную услугу.',
    'partners.ecosystems.hospitality.title': 'Решения для гостеприимства',
    'partners.ecosystems.hospitality.desc': 'Консьерж-телемедицина для гостей отеля — соединение с врачами прямо из номера.',
    'partners.ecosystems.footer': 'От дома до кампуса и путешествий, CEDEXX всегда под рукой.',
    'partners.form.badge': 'ПРИСОЕДИНИТЬСЯ К СЕТИ',
    'partners.form.title': 'Стать партнером Cedexx',
    'partners.form.subtitle': 'Узнайте о возможностях стратегической интеграции через наши ключевые направления и сети врачей.',
    'role.physician': 'Врач',
    'role.affiliate': 'Партнерская программа'
  },
  ht: {
    'nav.home': 'Akèy',
    'nav.about': 'Sou Nou',
    'nav.services': 'Sèvis',
    'nav.locations': 'Kote Nou Ye',
    'nav.blog': 'Blog Sante',
    'nav.partners': 'Patnè',
    'nav.contact': 'Kontak',
    'nav.pitch': 'Envestisè',
    'nav.enroll': 'Enskri Kounye a',
    'nav.schedule': 'Pran yon Demo',
    'seo.title': 'Cedexx | Pi Bon Swen. Isit la. Kounye a.',
    'seo.description': 'Yon sèvis byennèt premium ki konekte rezidan yo ak founisè endepandan sètifye pou swen chak jou, preskripsyon ak sipò.',
    'hero.title': 'Pi Bon Swen. Isit la. Kounye a.',
    'hero.subtitle': 'Aksè sante imedya nan pòch ou.',
    'hero.platform_desc': 'CEDEXX se yon platfòm aksè sante dijital ki konekte manm yo ak founisè endepandan ki gen lisans pou swen chak jou, preskripsyon, ak sipò byennèt mantal—tout atravè yon senp manm chak mwa.',
    'hero.amenity_desc': 'Yon ekipman byennèt modèn ki fèt pou moun, fanmi, ak kominote rezidansyèl yo.',
    'hero.cta1': 'Kòmanse Manm',
    'hero.cta2': 'Vin Patnè CEDEXX',
    'hero.cta3': 'Misyon Nou',
    'trust.label': 'Aksè sante serye ki fèt pou moun, fanmi, ak kominote rezidansyèl modèn.',
    'features.access.title': 'Aksè Founisè 24/7',
    'features.access.desc': 'Swen nenpòt lè, lajounen kou lannwit.',
    'features.speed.title': 'Wè yon Doktè nan Kèk Minit',
    'features.speed.desc': 'Konekte nan mwens pase 15 minit.',
    'features.membership.title': 'Yon Sèl Manm Senp',
    'features.membership.desc': '$14.99 moun / $34.99 fanmi.',
    'features.secure.title': 'Platfòm Sekirite ak Privye',
    'features.secure.desc': 'Konfòm ak HIPAA ak konfidansyèl.',
    'serve.title': 'Kat Poto Nou Yo',
    'serve.card1.title': 'Solisyon Ospitalite',
    'serve.card1.desc': 'Fasilite aksè nan sèvis konsyèj medikal pou envite otèl ou yo.',
    'serve.card1.cta': 'Aprann Plis',
    'serve.card2.title': 'Opòtinite Afilye',
    'serve.card2.desc': 'Patenarya telekominikasyon ak maketing ki fèt pou echèl.',
    'serve.card2.cta': 'Aprann Plis',
    'serve.card3.title': 'AKSESIBILITE',
    'serve.card3.desc': 'Konekte moun ki abite ak k ap travay ak aksè medikal imedya.',
    'serve.card3.cta': 'AKSESIBILITE',
    'serve.card4.title': 'Lojman Elèv/Kòporatif ak Multifanmi',
    'serve.card4.desc': 'Mete byen imobilye ou apa nan enkòpore valè aksè sante mobil.',
    'serve.card4.cta': 'Grandis Pwopriyete w',
    'pressure.title': 'Aksè Sante Sekirite',
    'how.title': 'Fèt pou Lavi Chak Jou',
    'how.step1.title': 'Konekte Touswit',
    'how.step1.desc': 'Tipikman konekte nan mwens pase 15 minit',
    'how.step2.title': 'Konsilte ak Founisè Yo',
    'how.step2.desc': 'Doktè sètifye nan kèk minit',
    'how.step3.title': 'Preskripsyon Dijital',
    'how.step3.desc': 'Voye touswit nan famasi ou',
    'outcomes.title': 'Yon Modèl Aksè Sante Ki Pi Entelijan',
    'outcomes.card1': 'Telemedsin 24/7',
    'outcomes.card2': 'Sipò Sante Mantal',
    'outcomes.card3': 'Aksè ak Preskripsyon',
    'why.title': 'Poukisa Cedexx Genyen',
    'why.f1': 'Yon Sèl App. Yon Sèl Manm.',
    'why.f2': 'Swen Imedya.',
    'why.f3': 'Pa Bezwen Asirans.',
    'why.f4': 'Pi Bon Swen. Isit la. Kounye a.',
    'disclaimer.text': 'Cedexx se yon platfòm teknoloji e li PA yon founisè swen sante. Nou pa bay konsèy medikal, dyagnostik oswa tretman. Tout founisè yo se antreprenè endepandan. Pou ijans, rele 911. Platfòm sa a pa ranplase asirans sante.',
    'contact.title': 'Kontakte Nou',
    'contact.subtitle': 'Kontakte ekip nou an epi n ap reponn ou nan yon jou travay.',
    'contact.name': 'Non Konplè',
    'contact.email': 'Adrès Imel',
    'contact.company': 'Konpayi / Òganizasyon',
    'contact.message': 'Mesaj',
    'contact.send': 'Voye Mesaj',
    'contact.sent': 'Mèsi! N ap kontakte w talè.',
    'footer.tagline': 'Pi Bon Swen. Isit la. Kounye a. Kenbe li nan pòch ou.',
    'footer.links': 'Lyen Rapid',
    'footer.contact': 'Kontak',
    'footer.legal': 'Legal',
    'footer.email': 'info@cedexx.net',
    'partners.cta': 'Antre nan Rezo Nou an',
    'plans.individual': '$14.99/pa mwa',
    'plans.family': '$34.99/pa mwa',
    'plans.family.desc': 'Kouvèti pou jiska 4 moun nan fanmi an',
    'partners.hero.title': 'Patenarya Estratejik',
    'partners.hero.subtitle': 'Pi Bon Swen. Isit la. Kounye a. Kenbe li nan pòch ou.',
    'partners.ecosystems.title': 'Ekosistèm Nou Sèvi',
    'partners.ecosystems.subtitle': 'Lidè endistri yo fè Cedexx konfyans pou fasilite aksè medikal imedya.',
    'partners.ecosystems.quote': 'Sante ta dwe deplase ak lavi modèn—imedya, fyab, ak aksesib kote moun ap viv, travay, vwayaje, ak grandi.',
    'partners.ecosystems.workforce.title': 'Transpòtasyon ak Travayè',
    'partners.ecosystems.workforce.desc': 'CEDEXX pèmèt aksè sante dijital modèn pou popilasyon travayè de tout kalite. Soti nan kamyon ak lojistik rive nan ospitalite ak ekip korporatif, nou bay koneksyon doktè abòdab ki adapte ak nenpòt orè.',
    'partners.ecosystems.individuals.title': 'Moun ak Fanmi',
    'partners.ecosystems.individuals.desc': 'Pou moun ak fanmi yo, CEDEXX bay yon kouch aksè pratik—si l ap konplete asirans ki egziste deja oswa l ap ofri koneksyon abòdab.',
    'partners.ecosystems.housing.title': 'Lojman ak Kominote',
    'partners.ecosystems.housing.desc': 'Atravè patenarya estratejik nan lojman elèv ak multifanmi, nou ede administratè yo prezante aksè medikal kòm yon sèvis premium.',
    'partners.ecosystems.hospitality.title': 'Poto Ospitalite',
    'partners.ecosystems.hospitality.desc': 'Ospitalite se twazyèm poto estratejik nou an, ki konekte vwayajè yo ak doktè sètifye nan konfò chanm yo.',
    'partners.ecosystems.footer': 'Soti nan kay rive nan kanpis ak vwayaj, CEDEXX kenbe aksè serye toupre ou.',
    'partners.form.badge': 'ANTRE NAN REZO A',
    'partners.form.title': 'Vin Patnè Cedexx',
    'partners.form.subtitle': 'Eksplore opòtinite entegrasyon estratejik atravè poto amènite nou yo ak rezo doktè nou yo.',
    'role.physician': 'Doktè',
    'role.affiliate': 'Patnè Afilye'
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string): string => translations[lang][key] ?? translations['en'][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
